# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-07 03:56
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cropping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Year', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='CropRequirements',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Fertility', models.DecimalField(decimal_places=5, default=1.0, max_digits=20)),
                ('Moisture_Content', models.DecimalField(decimal_places=5, default=1.0, max_digits=20)),
            ],
        ),
        migrations.CreateModel(
            name='Crops',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Farms',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Area', models.DecimalField(decimal_places=5, max_digits=90)),
                ('Points', django.contrib.gis.db.models.fields.PolygonField(srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='HouseHolds',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Monthly_Income', models.FloatField(blank=True, default=300.0, null=True)),
                ('Location_Id', django.contrib.gis.db.models.fields.PointField(default='POINT(1 1)', srid=4326)),
            ],
        ),
        migrations.CreateModel(
            name='Members',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=10)),
                ('DOB', models.DateTimeField()),
                ('Gender', models.CharField(max_length=1)),
                ('HouseHold_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itstask22.HouseHolds')),
            ],
        ),
        migrations.CreateModel(
            name='Photos',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Photo', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='Seasons',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Season', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Soils',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Soil', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Videos',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Video_Clip', models.CharField(max_length=100)),
                ('Household_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itstask22.HouseHolds')),
            ],
        ),
        migrations.CreateModel(
            name='Wells',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Depth', models.DecimalField(decimal_places=5, max_digits=20)),
                ('Location_Id', django.contrib.gis.db.models.fields.PointField(default='POINT(1 1)', srid=4326)),
                ('Photo_Id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Photos')),
            ],
        ),
        migrations.CreateModel(
            name='Yields',
            fields=[
                ('ID', models.IntegerField(primary_key=True, serialize=False)),
                ('Yield_Measure', models.DecimalField(decimal_places=5, max_digits=20)),
                ('Time', models.DateTimeField()),
                ('Well_Id', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Wells')),
            ],
        ),
        migrations.AddField(
            model_name='members',
            name='Photo_Id',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Photos'),
        ),
        migrations.AddField(
            model_name='farms',
            name='HouseHold_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itstask22.HouseHolds'),
        ),
        migrations.AddField(
            model_name='farms',
            name='Soil_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Soils'),
        ),
        migrations.AddField(
            model_name='croprequirements',
            name='Crop_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itstask22.Crops'),
        ),
        migrations.AddField(
            model_name='croprequirements',
            name='Season_Id',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itstask22.Seasons'),
        ),
        migrations.AddField(
            model_name='croprequirements',
            name='Soil_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Soils'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='Crop_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Crops'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='Farm_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Farms'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='Photo_Id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Photos'),
        ),
        migrations.AddField(
            model_name='cropping',
            name='Season_Id',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='itstask22.Seasons'),
        ),
        migrations.AlterUniqueTogether(
            name='yields',
            unique_together=set([('Well_Id', 'Time')]),
        ),
        migrations.AlterUniqueTogether(
            name='croprequirements',
            unique_together=set([('Crop_Id', 'Season_Id')]),
        ),
    ]
