# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:02
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itstask22', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='Location_Id',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT( 79.110090 13.222713 )', srid=4326),
        ),
    ]
