# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-11 10:07
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itstask22', '0002_auto_20171011_1002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='households',
            name='Location_Id',
            field=django.contrib.gis.db.models.fields.PointField(default='POINT( 13.222713 79.110090 )', srid=4326),
        ),
    ]
